pipeline {
  agent any

  options {
    timeout(time: 10, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "mrinternauta/node_app:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Build') {
      steps {
        script {
          dir("images/docker") {
            dockerImage = docker.build "${env.ARTIFACT_ID}"
          }
        }
      }
    }
    stage('Run tests') {
      steps {
        sh "docker run ${dockerImage.id} npm test"
      }
    }
    stage('Publish') {
      steps {
        script {
          docker.withRegistry("https://registry.hub.docker.com", "mrinternauta") {
            dockerImage.push()
          }
        }
      }
    }
    stage('Schedule Staging Deployment') {
      steps {
        build job: 'Node_app_test_deploy', parameters: [string(name: 'ARTIFACT_ID', value: "nodeapp")], wait: false
      }
    }
  }
}
